{{- if .Values.discovery.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.instanceName }}-tinycode-cross-namespace-discovery
  labels:
    app.kubernetes.io/name: tinycode
    app.kubernetes.io/instance: {{ .Values.instanceName }}
    app.kubernetes.io/managed-by: tinycode-operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
{{- end }}
