apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.instanceName }}-tinycode
  namespace: {{ .Values.instanceNamespace }}
  labels:
    app.kubernetes.io/name: tinycode
    app.kubernetes.io/instance: {{ .Values.instanceName }}
    app.kubernetes.io/managed-by: tinycode-operator
  annotations:
    tinycode.dev/instance: {{ .Values.instanceName }}
