---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instanceName }}-tinycode
  namespace: {{ .Values.instanceNamespace }}
  labels:
    app.kubernetes.io/name: tinycode
    app.kubernetes.io/instance: {{ .Values.instanceName }}
    app.kubernetes.io/managed-by: tinycode-operator
spec:
  selector:
    app.kubernetes.io/name: tinycode
    app.kubernetes.io/instance: {{ .Values.instanceName }}
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  type: ClusterIP
