---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tinycode-operator-manager
  namespace: tinycode-operator-system
  labels:
    app.kubernetes.io/name: tinycode-operator
    app.kubernetes.io/managed-by: tinycode-operator
